systemlist:
  none: "いろんなことに興味があります。環境はNixOS26.05 KDE Plasma6, Ubuntu Server 24.04.02, FreeBSD 14.4です。ESP32Forth v7.0.7.21, Orange Pi Zero 3 Armbianでも遊んでいます "
  NixOS: "LinuxMint22.3からNixOS26.05 KDE Plasma6へ移行しました。NixOSは経験がなかったのでなかなかたいへんでしたが、なんとか移行を完了しました。 \n \
  構成要素（vscode/go/mysql, LibreOffice, Gimp/Incscape, Qemu/KVM(Windows11Pro), Incus, distrobox/ubuntu(Windows版LINEなど), Joplin/Obsidian） \n \
  設定ファイルは以下のように機能ごとに分割して作成しています。 \n \
``` \n \ 
flake.nix \n \
cofiguration.nix \n \
hardware-configuration.nix \n \
home.nix # Home Manager設定 \n \
modules/ \n \
├── desktop.nix      # デスクトップ環境 \n \
├── filesystems.nix  # ファイルシステム(btrfs)設定 \n \
├── containers.nix   # コンテナ設定 \n \
├── qemukvm.nix      # コンテナ(KVM)設定 \n \
├── networking.nix   # ネットワーク設定 \n \
└── service.nix      # サービス設定 \n \
└── system.nix       # システム設定 \n \
└── backup.nix       # MySQLバックアップ設定 \n \
└── neovim/ \n \
.     └── default.nix \n \
.     └── opts.nix       # 基本設定 \n \
.     └── keymaps.nix    # キーマップ設定 \n \
.     └── plugin.nix     # プラグイン設定 \n \
``` \n \
"
  Go: "あなたはGoのエクスパート。開発環境はNixOS26.05、実行環境はubuntu server 24.04.2 LTS、Go1.26.3、net/http+go-template、DBはMySQL Ver 8.0.41-0をgorpでアクセス。"
  ESP32: "LinuxMint22.3上でvscode+PlatformIO+ESP-IDFを使ってプログラムを開発します。ただしESP32forthだけはArduino IDEでコンパイルしています。ボードはESP32-WROOM32とESP32-S3です。"
  Arduino: "あなたは Arduino のエキスパート。開発にはvscode+PlatformIOを使っています。"
  OPi: "あなたは Orange Pi Zero 3のエキスパート。OSはArmbianで開発はGo 1.25.5 + 1 Periph.io(LinuxMint vscodeでクロスコンパイル、delveでデバッグ)を使っています。"

venderlist:
  Google:
    evapi: "GOOGLE_API_KEY"
    apikey: ""
    url: "https://generativelanguage.googleapis.com/v1beta/models/"
  Anthropic:
    evapi: "CLAUDE_API_KEY"
    apikey: ""
    url: "https://api.anthropic.com/v1/messages"
  DeepSeek:
    evapi: "DEEPSEEK_API_KEY"
    apikey: ""
    url: "https://api.deepseek.com/v1/chat/completions"
  OpenAI:
    evapi: "OPENAI_API_KEY"
    apikey: ""
    url: "https://api.openai.com/v1/chat/completions"
  Moonshot:
    evapi: "MOONSHOT_API_KEY"
    apikey: ""
    url: "https://api.moonshot.ai/v1/chat/completions"

modellist:
  gemini-2.5-flash-lite-preview-09-2025:
    comment: "$0.40"
    model: "gemini"
    vendor: "Google"
  gemini-2.5-flash-lite:
    comment: "$0.40"
    model: "gemini"
    vendor: "Google"
  gemini-2.5-flash:
    comment: "$2.50"
    model: "gemini"
    vendor: "Google"
  gemini-2.5-pro:
    comment: "$10.00/$15.00"
    model: "gemini"
    vendor: "Google"
  gemini-3-flash-preview:
    comment: "$3.00"
    model: "gemini"
    vendor: "Google"
  gemini-3-flash-lite-preview:
    comment: "$1.50"
    model: "gemini"
    vendor: "Google"
  gemini-3.1-pro-preview:
    comment: "$12.00/$18.00"
    model: "gemini"
    vendor: "Google"
  claude-haiku-4-5-20251001:
    comment: "$5"
    model: "claude"
    vendor: "Anthropic"
  claude-sonnet-4.6:
    comment: "$15"
    model: "claude"
    vendor: "Anthropic"
  claude-opus-4-7:
    comment: "$25"
    model: "claude"
    vendor: "Anthropic"
  deepseek-v4-flash:
    comment: "$0.28"
    model: "openai"
    vendor: "DeepSeek"
  deepseek-v4-pro:
    comment: "$0.87/$3.48"
    model: "openai"
    vendor: "DeepSeek"
  gpt-5.4-nano:
    comment: "$1.25"
    model: "openai"
    vendor: "OpenAI"
  gpt-5.4-mini:
    comment: "$4.50"
    model: "openai"
    vendor: "OpenAI"
  gpt-5.4:
    comment: "$15.00"
    model: "openai2"
    vendor: "OpenAI"
  kimi-k2.6:
    comment: "$4.00"
    model: "moonshot"
    vendor: "Moonshot"